import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "sajiddev.is-a.dev",
  title: "Sajid | Bringing Ideas to Reality ✨",
  description:
    "Hi, I'm Sajid - Got ideas you are itching to bring to life? Let's collaborate and make it happen!",
  keywords: [
    // Personal & Branding
    "sajid hussain",
    "sajid",
    "sajid portfolio",
    "sajid portfolio 2024",
    "sajid portfolio 2025",
    "sajid hussain portfolio",
    "sajid hussain portfolio 2024",
    "sajid hussain portfolio 2025",
    "sajid hussain website",
    "sajid hussain personal website",
    "sajid hussain portfolio site",
    "sajiddev",
    "sajiddev portfolio",
    "sajiddev portfolio 2024",
    "sajiddev portfolio 2025",
    "sajiddev.in",
    "sajiddev.is-a.dev",
    "sajid hussain developer",
    "sajid full stack developer",
    "sajid frontend developer",
    "sajid react developer",
    "sajid nextjs developer",
    "sajid fullstack portfolio",
    "sajid hussain software engineer",
    "sajid hussain full stack engineer",
    "sajid hussain next.js engineer",
    "sajid creative developer",
    "sajid ui developer",
    "sajid ux engineer",
    "sajid software portfolio",
    "sajid engineer portfolio",
    "sajid hussain github",
    "sajid hussain linkedin",
    "sajid hussain dev portfolio",
    "sajid website developer",
    "sajid professional portfolio",
    "sajid web engineer",
    "sajid software portfolio 2024",
    "sajid software portfolio 2025",
    "hire sajid hussain",
    "hire sajid developer",
    "hire full stack developer sajid",
    "hire react developer sajid",
    "hire nextjs developer sajid",

    // Frontend Development
    "frontend developer",
    "frontend engineer",
    "frontend developer india",
    "frontend developer 2025",
    "frontend developer react",
    "frontend developer next.js",
    "frontend engineer react",
    "frontend developer portfolio",
    "modern frontend developer",
    "nextjs frontend developer",
    "typescript frontend developer",
    "html css javascript developer",
    "react frontend engineer",
    "modern ui developer",
    "creative frontend developer",
    "frontend developer in bengaluru",
    "frontend engineer portfolio",
    "frontend dev projects",
    "frontend react expert",
    "frontend nextjs expert",
    "responsive frontend developer",
    "tailwindcss developer",
    "bootstrap frontend developer",
    "scss frontend developer",

    // Full Stack Development
    "full stack developer",
    "full stack engineer",
    "full stack web developer",
    "full stack developer 2024",
    "full stack developer 2025",
    "full stack developer portfolio",
    "mern stack developer",
    "mern full stack developer",
    "nextjs full stack developer",
    "react node full stack developer",
    "react express full stack developer",
    "full stack developer in india",
    "typescript full stack developer",
    "javascript full stack engineer",
    "next full stack engineer",
    "nodejs full stack developer",
    "full stack dev projects",
    "backend frontend developer",
    "react next node developer",
    "modern full stack developer",
    "microservices full stack developer",
    "api integration developer",

    // Web Developer Keywords
    "web developer",
    "web engineer",
    "web app developer",
    "web application developer",
    "web designer",
    "frontend web developer",
    "backend web developer",
    "modern web developer",
    "creative web developer",
    "javascript web developer",
    "next.js web developer",
    "react web developer",
    "nodejs web developer",
    "full stack web developer",
    "responsive web developer",
    "modern ui web developer",
    "professional web developer",
    "portfolio web developer",
    "personal web developer site",
    "custom website developer",
    "landing page developer",
    "frontend web engineer",
    "freelance web developer",
    "hire web developer india",
    "hire web developer bengaluru",
    "web developer portfolio 2024",
    "web developer portfolio 2025",

    // React Developer Keywords
    "react developer",
    "react engineer",
    "reactjs developer",
    "react.js developer",
    "react developer india",
    "react developer portfolio",
    "react developer 2024",
    "react developer 2025",
    "react ui developer",
    "react frontend developer",
    "react full stack developer",
    "react node developer",
    "react next developer",
    "react expert",
    "react specialist",
    "react hooks developer",
    "react typescript developer",
    "react tailwind developer",
    "react redux developer",
    "react developer projects",
    "hire react developer",
    "react app developer",
    "react single page developer",

    // Next.js Developer Keywords
    "next.js developer",
    "nextjs developer",
    "nextjs full stack developer",
    "nextjs engineer",
    "nextjs frontend developer",
    "nextjs backend developer",
    "nextjs developer india",
    "nextjs developer portfolio",
    "nextjs developer 2024",
    "nextjs developer 2025",
    "nextjs developer projects",
    "nextjs react developer",
    "nextjs node developer",
    "nextjs tailwind developer",
    "hire nextjs developer",
    "nextjs app developer",
    "nextjs website developer",
    "nextjs landing page developer",

    // Backend & DevOps
    "nodejs developer",
    "express developer",
    "api developer",
    "backend developer",
    "backend engineer",
    "backend developer india",
    "rest api developer",
    "microservices developer",
    "eda architecture developer",
    "server developer",
    "docker developer",
    "devops engineer",
    "devops developer",
    "aws developer",
    "aws full stack developer",
    "cloud developer",
    "cloud engineer",
    "ci/cd engineer",
    "redis developer",
    "rabbitmq developer",
    "mongodb developer",
    "postgresql developer",
    "firebase developer",
    "supabase developer",
    "neon database developer",
    "lambda developer",
    "beanstalk engineer",
    "ec2 engineer",

    // UI/UX & Design
    "ui developer",
    "ux developer",
    "ui designer",
    "ux designer",
    "frontend designer",
    "creative ui developer",
    "modern ui designer",
    "responsive ui developer",
    "animation developer",
    "framer motion developer",
    "gsap developer",
    "shadcn ui developer",
    "headless ui developer",
    "component library developer",

    // Tools & Platforms
    "vscode developer",
    "git developer",
    "github developer",
    "vercel developer",
    "vercel deployment",
    "firebase hosting developer",
    "aws deployment engineer",
    "cloudflare developer",
    "api integration developer",
    "clerk auth developer",
    "nextauth developer",
    "jwt authentication developer",
    "typescript developer",
    "javascript developer",
    "html developer",
    "css developer",
    "scss developer",
    "bootstrap developer",
    "tailwindcss designer",

    // SEO / Portfolio Specific
    "developer portfolio website",
    "modern portfolio 2024",
    "modern portfolio 2025",
    "react portfolio website",
    "nextjs portfolio website",
    "full stack portfolio website",
    "responsive developer portfolio",
    "personal developer website",
    "developer portfolio inspiration",
    "frontend developer portfolio website",
    "nextjs 15 developer",
    "typescript nextjs developer",
    "modern web engineer 2025",
    "creative software developer 2025",
    "next.js 15 full stack developer",
    "next 15 react developer",
    "ai powered portfolio developer",
    "sajid ai portfolio",
    "sajid nextjs 15 developer",
    "sajid react 19 developer",
    "web engineer india 2025",
    "frontend engineer india 2025",
    "software engineer portfolio 2025",
    "web app engineer",
    "modern website builder",
    "frontend mentor developer",
    "full stack javascript developer",
    "typescript engineer 2025",
    "next react ts developer",
    "developer based in bengaluru",
    "developer based in india",
    "freelance developer 2025",
    "open source contributor sajid",
    "open source developer india",
    "react open source developer",
    "nextjs open source contributor",
    "modern web apps developer",
    "web tools developer",
    "portfolio website 2025",
    "personal website 2025",
    "sajid professional website",
    "sajid personal site",
    "modern portfolio india",
    "full stack developer india",
    "frontend developer india 2025",
    "react developer india 2025",
    "nextjs developer india 2025",
    "node developer india 2025",
    "software engineer bengaluru",
    "frontend engineer bengaluru",
    "full stack engineer bengaluru",
    "react next full stack engineer",
    "nextjs tailwind developer india",
    "modern ui developer india",
    "creative web engineer india",
    "developer hiring 2025",
    "portfolio website inspiration 2025",
    "best developer portfolios 2025",
    "developer showcase site 2025",
    "software engineer website 2025",
    "react js engineer portfolio",
    "next js engineer portfolio",
    "web designer portfolio india",
    "ui ux engineer india",
    "frontend dev 2025",
    "fullstack dev 2025",
    "react nextjs developer india",
    "javascript engineer 2025",
    "typescript engineer india",
    "modern web builder 2025",
    "creative technologist 2025",
    "cloud full stack engineer 2025",
    "aws full stack developer india",
    "microservices developer india",
    "docker kubernetes developer",
    "devops full stack engineer 2025",
  ],
  siteUrl: "https://sajiddev.is-a.dev",
  creator: {
    name: "Sajid Hussain",
    url: "https://sajiddev.is-a.dev",
  },
  ogImage: "/",
  links: {
    x: "https://x.com/",
    github: "https://github.com/Sajid-tech",
  },
};
